DROP TABLE IF EXISTS "Bitcoin";
DROP TABLE IF EXISTS "Bitcoin_cash";
DROP TABLE IF EXISTS "Ethereum";
DROP TABLE IF EXISTS "Binance";
DROP TABLE IF EXISTS "Toncoin";
DROP TABLE IF EXISTS "usdc_coin";
DROP TABLE IF EXISTS "Cardano";
DROP TABLE IF EXISTS "Avalanche";
DROP TABLE IF EXISTS "Polygon";
DROP TABLE IF EXISTS "Chainlink";
DROP TABLE IF EXISTS "shiba_inu";
DROP TABLE IF EXISTS "Polkadot";
DROP TABLE IF EXISTS "Wrapped_Bitcoin";
DROP TABLE IF EXISTS "Tether";
DROP TABLE IF EXISTS "tron";
DROP TABLE IF EXISTS "Wrapped_TRON";
DROP TABLE IF EXISTS "Solana";
DROP TABLE IF EXISTS "xrp";
DROP TABLE IF EXISTS "dodge";
DROP TABLE IF EXISTS "steth";

CREATE TABLE "Bitcoin" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);

CREATE TABLE "Bitcoin_cash" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);

CREATE TABLE "Ethereum" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);

CREATE TABLE "Binance" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);

CREATE TABLE "Toncoin" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "usdc_coin" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Cardano" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Avalanche" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Polygon" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Chainlink" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "shiba_inu" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Polkadot" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);

CREATE TABLE "Wrapped_Bitcoin" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Tether" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "tron" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Wrapped_TRON" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "Solana" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "xrp" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "dodge" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);
CREATE TABLE "steth" (
    "Date" VARCHAR(15) PRIMARY KEY NOT NULL,
    "Open" FLOAT NOT NULL,
	"High" FLOAT NOT NULL,
	"Low" FLOAT  NOT NULL,
	"Close" FLOAT NOT NULL,
	"Adj Close" FLOAT  NOT NULL,
	"Volume" FLOAT NOT NULL
);



select * from "Bitcoin" limit 10;
select * from "Chainlink" limit 10;
select * from "steth" limit 10;
